#! /bin/bash
# Copyright © 2013, naingenieu <nain dot genieu at gmail dot com>
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

# This bash script take an vine.co url, download the corresponding video and turn it into a gif 

while [ $# -gt 0 ]
	do
   		case "$1" in
		-o)  gif="$2"; shift;;
		-u)  url="$2"; shift;;
		-s)  saveflag="save";;
		--)  shift; break;;
		-*)
    			echo >&2 \
    			"usage: $0 [-u url] url de l'image <-o nom du gif> nom du gif en sortie] <-s> sauvegarde de la video"
    			return 1;;
		*)  break;;
   			esac
   		shift;
	done;

if [ -z $url ]; then
	echo >&2 "usage: $0 [-u url] url de l'image <-o nom du gif> nom du gif en sortie] <-s> sauvegarde de la video"
	return 1
fi
videourl=$(GET $url | grep stream | grep http | cut -d '"' -f4 | cut -d '?' -f1 )
videoname=$( echo $url | cut -d '/' -f5)
echo "Téléchargement en cours..."
wget $(GET $url | grep stream | grep http | cut -d '"' -f4 | cut -d '?' -f1 ) -q -O $videoname
echo "Téléchargement terminé"
echo "Conversion en cours..."
mplayer -vo gif89a $videoname > /dev/null 2>&1
echo "Conversion terminé"
echo "Script par naingenieu"

if [ ! -z $gif ]; then
	mv out.gif $gif
else
	mv out.gif $videoname".gif"
fi
if [  ! $sauveflag = "save" ]; then
	rm -f $videoname
fi
